#index:
#    path: /
#    controller: App\Controller\DefaultController::index
app_weather_prediction:
  path: /api/prediction/{date}
  controller: App\Controller\PredictionController::index
  methods: GET